# Generated by Django 4.1.2 on 2022-10-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humidite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plante',
            name='unixtime_val',
            field=models.FloatField(default=1665759839, max_length=15),
            preserve_default=False,
        ),
    ]
