# Generated by Django 4.1.2 on 2022-10-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Humidite', '0002_plante_unixtime_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plante',
            name='unixtime_val',
        ),
    ]
