# Generated by Django 4.1.2 on 2022-12-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humidite', '0002_plante_humidite_val_plante_temperature_val_plante_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.IntegerField(null=True)),
                ('touch_val', models.BooleanField(null=True)),
                ('lumiere_val', models.BooleanField(null=True)),
            ],
        ),
    ]
