# Generated by Django 4.1.2 on 2022-12-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humidite', '0003_touch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touch',
            name='lumiere_val',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='touch',
            name='touch_val',
            field=models.IntegerField(null=True),
        ),
    ]
