# Generated by Django 4.1.2 on 2022-10-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humidite', '0003_remove_plante_unixtime_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='plante',
            name='unixtime_val',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
